on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        uses: actions/hello-world-docker-action@v2
        with:
          image: 'container'
          context: './test'
          folder: './deploy'
          destination: ${{ secrets.SSH_URL }}
          destination_key: ${{ secrets.SSH_KEY }}
