on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test action
    steps:
      - name: Test action
        uses: ./
        with:
          image: 'container'
          context: './test'
          folder: './deploy'
          destination: ${{ secrets.SSH_URL }}
          destination_key: ${{ secrets.SSH_KEY }}
